export const urows = [
  {
    id: 1,
    name: 'Jennifer Doe',
    emailraw: 'jennifer.doe@rockequity.com',
    role: 'Admin',
    firmId: 1,
    hasRoles: [1],
    adminRoles: [1, 2 ,3, 4, 5, 6, 7, 8, 9, 10],
    collaboratorRoles: [],
    viewerRoles: [],
    firmAdmin: false,
    companies: [],
    collaboratorRoles: [],
    viewerRoles: [],
    firmAdmin: false,
    
  },
  {
    id: 2,
    name: 'Ryan Tse',
    emailraw: 'ryan.tse@rockequity.com',
    role: 'Collaborator',
    firmId: 1,
    hasRoles: [1],
    adminRoles: [],
    collaboratorRoles: [1, 2 ,3, 4, 5, 6, 7, 8, 9, 10],
    viewerRoles: [],
    firmAdmin: false,
    
  },
  {
    id: 3,
    name: 'Jane Rach',
    emailraw: 'jane.rach@rockequity.com',
    role: 'User',
    firmId: 1,
    hasRoles: [1],
    adminRoles: [],
    collaboratorRoles: [],
    viewerRoles: [],
    firmAdmin: false,
    
  },
  {
    id: 4,
    name: 'Eric Eay',
    emailraw: 'eric@cpa-QofE.com',
    role: 'User',
    firmId: 1,
    hasRoles: [1],
    adminRoles: [],
    collaboratorRoles: [],
    viewerRoles: [],
    firmAdmin: false,
    
  },
  {
    id: 5,
    name: 'Jack Plence',
    emailraw: 'jack@fastserv.com',
    role: 'Collaborator',
    firmId: 1,
    hasRoles: [1],
    adminRoles: [],
    collaboratorRoles: [1, 2 ,3, 4, 5, 6, 7, 8, 9, 10],
    viewerRoles: [],
    firmAdmin: false,
    
  },
  {
    id: 6,
    name: 'Tiger Nixon',
    emailraw: 'tiger.nixon@gmail.com',
    role: 'External User',
    firmId: 1,
    hasRoles: [1],
    adminRoles: [],
    collaboratorRoles: [],
    viewerRoles: [],
    firmAdmin: false,
    
  },
  {
    id: 7,
    name: 'Sonya Frost',
    emailraw: 'sfrost@gmail.com',
    role: 'External User',
    firmId: 1,
    hasRoles: [1],
    adminRoles: [],
    collaboratorRoles: [],
    viewerRoles: [],
    firmAdmin: false,
    
  },
  {
    id: 8,
    name: 'Tatyana Fitzpatrick',
    emailraw: 'tfitz@gmail.com',
    role: 'External User',
    firmId: 1,
    hasRoles: [1],
    adminRoles: [],
    collaboratorRoles: [],
    viewerRoles: [],
    firmAdmin: false,
    
  },
]

export const ucols = [
  { label: 'Name', field: 'name' },
  { label: 'Email', field: 'email' },
  { label: 'Role', field: 'role' },
  { label: 'Actions', field: 'buttons', sort: false },
]