export const urows = [
  {
    id: '1',
    name: 'Jennifer Doe',
    emailraw: 'jennifer.doe@rockequity.com',
    role: 'Admin',
    firmId: '1',
    adminRoles: ['1'],
    hasRoles: ['1'],
  },
  {
    id: '2',
    name: 'Ryan Tse',
    emailraw: 'ryan.tse@rockequity.com',
    role: 'Collaborator',
    firmId: '1',
    adminRoles: [],
    hasRoles: ['1'],
  },
  {
    id: '3',
    name: 'Jane Rach',
    emailraw: 'jane.rach@rockequity.com',
    role: 'User',
    firmId: '1',
    adminRoles: [],
    hasRoles: ['1'],
  },
  {
    id: '4',
    name: 'Eric Eay',
    emailraw: 'eric@cpa-QofE.com',
    role: 'User',
    firmId: '1',
    adminRoles: [],
    hasRoles: ['1'],
  },
  {
    id: '5',
    name: 'Jack Plence',
    emailraw: 'jack@fastserv.com',
    role: 'Collaborator',
    firmId: '1',
    adminRoles: [],
    hasRoles: ['1'],
  },
  {
    id: '6',
    name: 'Tiger Nixon',
    emailraw: 'tiger.nixon@gmail.com',
    role: 'External User',
    firmId: '1',
    adminRoles: [],
    hasRoles: ['1'],
  },
  {
    id: '7',
    name: 'Sonya Frost',
    emailraw: 'sfrost@gmail.com',
    role: 'External User',
    firmId: '1',
    adminRoles: [],
    hasRoles: ['1'],
  },
  {
    id: '8',
    name: 'Tatyana Fitzpatrick',
    emailraw: 'tfitz@gmail.com',
    role: 'External User',
    firmId: '1',
    adminRoles: [],
    hasRoles: ['1'],
  },
]

export const ucols = [
  { label: 'Name', field: 'name' },
  { label: 'Email', field: 'email' },
  { label: 'Role', field: 'role' },
  { label: 'Actions', field: 'buttons', sort: false },
]